<div class="pdp-editor-note">
	<div class="note-content">
		<ul>
			<li>Jonathan Simkhai</li>
			<li>Blazers</li>
			<li>Viscose</li>
		</ul>
		<div class="author-text">
			<h3>a note from the editor</h3>
			<p>The Forte Lurex Linen Viscose Jacket in Mother of Pearl features lunar lavishness by night and by day: a blazer in a linen blend shot with lurex for a shimmering surface that shines like a star in the sky. </p>
			<div class="name">By <span>MINNA SHIM</span>, Fashion Editor</div>
		</div>
	</div>
</div>